### ISSUE TITLE
Very nice script, do you think we can extend it to be used more dynamically providing the courses ids as input ?

### ISSUE THREAD

**Issue by ahmeddrawy** [Marwa64/Automate-Lab-Attendance#1]
also where do you deployed this code to be scheduled ?

**Comment by Marwa64** [comment]
I think it might be possible using Blackboard's API, I'll try to read through their documentation to see if I can implement that.
And I didn't deploy it, I just keep the script running in the background and [these](https://github.com/Marwa64/Automate-Lab-Attendance/blob/888cca8b2a482524ffbaba3590ff1667cbc3d997/Attend%20Labs.py#L58-L60) functions execute it at the specified time

**Comment by ahmeddrawy** [comment]
so you keep your pc running the script all the time? 
you can easily deploy it to lambda function in aws 
i can help you extending this to be runnable as a linux command

**Comment by Marwa64** [comment]
I'll check out lambda functions in aws, thanks for the suggestion!
And I use Windows
