### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TawfikYasser** [Marwa64/Automate-Lab-Attendance#2]
Hi

I Suggest to add function return type to the function header and arguments type also, Like this below:

```python

def function(arg:str) -> str:
    body
    ....
```

I can do that if you tell me the return for each function and the args type.

Thanks

**Comment by Marwa64** [comment]
I added the arguments type, and both functions don't return anything they're void

**Comment by TawfikYasser** [comment]
Okay, So if the function returns void it good to make it like this: def function () -> None:

**Comment by Marwa64** [comment]
Ahh okay done
